"""
export_js.py
------------
Generate pwhl-data.js from the three WAR CSVs.

Run from Projects/PWHL_war/:
    /c/Users/morga/AppData/Local/Python/bin/python.exe export_js.py
"""

import json
import sys
from pathlib import Path

import pandas as pd

OUT_PATH = Path("pwhl_war_data_export.js")
PORTFOLIO_PATH = Path("../../portfolio/js/pwhl-data.js")

SEASONS = [
    ("2023-24", 2023, "pwhl_war/data/war_2324.csv", 100.0),
    ("2024-25", 2024, "pwhl_war/data/war_2425.csv", 100.0),
    ("2025-26", 2025, "pwhl_war/data/war_2526.csv",  50.0),
]

ROUND = {
    "toi":     3,
    "ixG":     3,
    "oxg60":   4,
    "owar":    3,
    "dwar":    3,
    "war":     3,
    "war60":   3,
    "ozs_pct": 4,
}


def normalize_pos(p: str) -> str:
    return "D" if str(p).upper() in {"LD", "RD", "D"} else "F"


def load_season(csv_path: str, season_key: int, min_toi: float) -> list[dict]:
    df = pd.read_csv(csv_path)
    df = df[df["toi_min"] >= min_toi].copy()

    rows = []
    for _, r in df.iterrows():
        row = {
            "id":      int(r["player_id"]),
            "name":    str(r["name"]),
            "team":    str(r["team"]),
            "pos":     normalize_pos(r["pos"]),
            "season":  season_key,
            "gp":      int(r["gp"]),
            "toi":     round(float(r["toi_min"]),     ROUND["toi"]),
            "G":       int(r["G"]),
            "A1":      int(r["A1"]),
            "A2":      int(r["A2"]),
            "ixG":     round(float(r["total_ixG"]),   ROUND["ixG"]),
            "oxg60":   round(float(r["o_xG60"]),      ROUND["oxg60"]),
            "owar":    round(float(r["oWAR"]),         ROUND["owar"]),
            "dwar":    round(float(r["dWAR"]),         ROUND["dwar"]),
            "war":     round(float(r["WAR"]),          ROUND["war"]),
            "war60":   round(float(r["war60"]),        ROUND["war60"]),
            "ozs_pct": round(float(r.get("ozs_pct", 0.5) or 0.5), ROUND["ozs_pct"]),
        }
        rows.append(row)

    rows.sort(key=lambda x: x["war"], reverse=True)
    return rows


def main() -> None:
    data: dict[int, list] = {}

    for season_str, season_key, csv_path, min_toi in SEASONS:
        p = Path(csv_path)
        if not p.exists():
            print(f"SKIP {season_str}: {csv_path} not found", file=sys.stderr)
            continue
        rows = load_season(csv_path, season_key, min_toi)
        data[season_key] = rows
        print(f"  {season_str}: {len(rows)} players (toi >= {min_toi:.0f} min)")

    lines = ["// pwhl-data.js — generated by Projects/PWHL_war inline script"]
    lines.append("const PWHL_DATA = {")

    season_keys = sorted(data.keys())
    for i, sk in enumerate(season_keys):
        comma = "," if i < len(season_keys) - 1 else ""
        rows_js = json.dumps(data[sk], separators=(",", ":"), ensure_ascii=False)
        # Indent the array one level
        rows_js = rows_js.replace("[{", "[\n    {").replace("},{", "},\n    {").replace("}]", "}\n  ]")
        lines.append(f"  {sk}: {rows_js}{comma}")

    lines.append("};")
    js_content = "\n".join(lines) + "\n"

    OUT_PATH.write_text(js_content, encoding="utf-8")
    print(f"Written: {OUT_PATH}")

    if PORTFOLIO_PATH.parent.exists():
        PORTFOLIO_PATH.write_text(js_content, encoding="utf-8")
        print(f"Copied:  {PORTFOLIO_PATH}")
    else:
        print(f"Portfolio path not found, skipping copy: {PORTFOLIO_PATH}")


if __name__ == "__main__":
    main()
